"""Bundled life tables and loaders."""

from __future__ import annotations

from pathlib import Path
from typing import Optional

import pandas as pd

from ..lifetable import LifeTable
from ..fractional import FractionalAge

_DATA_DIR = Path(__file__).parent
_TABUAS_DIR = _DATA_DIR / "tabuas_csv"


def list_tables() -> list[str]:
    """Return names of all available bundled tables."""
    from_root = sorted(p.stem for p in _DATA_DIR.glob("*.csv"))
    from_tabuas = sorted(p.stem for p in _TABUAS_DIR.glob("*.csv"))
    from_parquet = sorted(p.stem for p in _DATA_DIR.glob("*.parquet"))
    return from_root + from_tabuas + from_parquet


def load_table(
    name: str,
    fractional: FractionalAge = FractionalAge.UDD,
    column: Optional[str] = None,
) -> LifeTable:
    """
    Load a bundled life table by name.

    Parameters
    ----------
    name : str
        Table identifier. Use ``list_tables()`` to see all available tables.

        Root tables: ``"soa_ilt"``

        Brazilian EMS tables (in ``tabuas_csv/``):
        ``"br_emssb_2021_m"``, ``"br_emssb_2021_f"``,
        ``"br_emsmt_2021_m"``, ``"br_emsmt_2021_f"``, etc.

        R-sourced tables (generated by ``scripts/convert_rda_to_parquet.py``):
        ``"soa08"``, ``"AM92Lt"``, ``"AF92Lt"``,
        ``"demoUsa"``, ``"demoUk"``, ``"demoIta"``, ``"demoFrance"``,
        ``"demoGermany"``, ``"demoJapan"``, ``"demoChina"``, ``"demoCanada"``

    fractional : FractionalAge
        Fractional-age assumption to attach to the returned LifeTable.

    column : str, optional
        For multi-column parquet tables (``demo*``), the data column to use as
        ``lx`` or ``qx``.  If omitted and only one data column exists the column
        is chosen automatically.  If omitted and multiple columns exist, a
        ``ValueError`` is raised listing the available column names.

        Example::

            load_table("demoUsa", column="USSS2007M")
            load_table("demoGermany", column="qxMale")

    Returns
    -------
    LifeTable
    """
    # ------------------------------------------------------------------ #
    # Root CSV (soa_ilt.csv)                                              #
    # ------------------------------------------------------------------ #
    root_csv = _DATA_DIR / f"{name}.csv"
    if root_csv.exists():
        df = pd.read_csv(root_csv)
        return LifeTable.from_dataframe(
            df, age_col="age", qx_col="qx", name=name, fractional=fractional
        )

    # ------------------------------------------------------------------ #
    # tabuas_csv/ — dynamic discovery                                     #
    # ------------------------------------------------------------------ #
    tabua_csv = _TABUAS_DIR / f"{name}.csv"
    if tabua_csv.exists():
        df = pd.read_csv(tabua_csv)
        return LifeTable.from_dataframe(
            df, age_col="age", qx_col="qx", name=name, fractional=fractional
        )

    # ------------------------------------------------------------------ #
    # Parquet tables (R-sourced)                                          #
    # ------------------------------------------------------------------ #
    parquet_path = _DATA_DIR / f"{name}.parquet"
    if parquet_path.exists():
        df = pd.read_parquet(parquet_path)
        data_cols = [c for c in df.columns if c != "age"]

        if len(data_cols) == 1:
            col = data_cols[0]
        elif column is not None:
            if column not in data_cols:
                raise ValueError(
                    f"Column '{column}' not found in '{name}'. "
                    f"Available: {data_cols}"
                )
            col = column
        else:
            raise ValueError(
                f"'{name}' contains multiple data columns — specify one with "
                f"column=<name>.\nAvailable: {data_cols}"
            )

        col_name = f"{name}/{col}"
        sample = df[col].dropna()
        if sample.max() >= 2.0:
            return LifeTable.from_dataframe(
                df[["age", col]].rename(columns={col: "lx"}),
                age_col="age", lx_col="lx", name=col_name, fractional=fractional,
            )
        else:
            return LifeTable.from_dataframe(
                df[["age", col]].rename(columns={col: "qx"}),
                age_col="age", qx_col="qx", name=col_name, fractional=fractional,
            )

    raise KeyError(
        f"Table '{name}' not found. Use list_tables() to see available tables."
    )


def list_columns(name: str) -> list[str]:
    """
    Return the data columns available in a multi-column parquet table.

    Useful for ``demo*`` tables which bundle several life tables in one file.

    Example
    -------
    >>> list_columns("demoUsa")
    ['USSS2007M', 'USSS2007F', 'USSS2000M', 'USSS2000F', 'USSS1990M', 'USSS1990F']
    """
    parquet_path = _DATA_DIR / f"{name}.parquet"
    if not parquet_path.exists():
        raise ValueError(f"No parquet file found for '{name}'")
    df = pd.read_parquet(parquet_path, columns=None)
    return [c for c in df.columns if c != "age"]
