"""Bundled life tables and loaders."""

from __future__ import annotations

import importlib.resources
from pathlib import Path
from typing import Optional

import pandas as pd

from ..lifetable import LifeTable
from ..fractional import FractionalAge

_DATA_DIR = Path(__file__).parent

_BUILTIN_TABLES = {
    # SOA Illustrative Life Table (Bowers et al., ages 0–99)
    "soa_ilt": "soa_ilt.csv",
    # BR-EMS 2021 (ages 0–117/116)
    "br_emssb_2021_m": "br_emssb_2021_m.csv",
    "br_emssb_2021_f": "br_emssb_2021_f.csv",
    "br_emsmt_2021_m": "br_emsmt_2021_m.csv",
    "br_emsmt_2021_f": "br_emsmt_2021_f.csv",
    # BR-EMS 2015 (ages 0–119)
    "br_emssb_2015_m": "br_emssb_2015_m.csv",
    "br_emssb_2015_f": "br_emssb_2015_f.csv",
    "br_emsmt_2015_m": "br_emsmt_2015_m.csv",
    "br_emsmt_2015_f": "br_emsmt_2015_f.csv",
    # BR-EMS 2010 (ages 0–116/113)
    "br_emssb_2010_m": "br_emssb_2010_m.csv",
    "br_emssb_2010_f": "br_emssb_2010_f.csv",
    "br_emsmt_2010_m": "br_emsmt_2010_m.csv",
    "br_emsmt_2010_f": "br_emsmt_2010_f.csv",
}


def load_table(
    name: str,
    fractional: FractionalAge = FractionalAge.UDD,
) -> LifeTable:
    """
    Load a bundled life table by name.

    Parameters
    ----------
    name : str
        Table identifier. Built-in tables:

        - ``"soa_ilt"`` — SOA Illustrative Life Table (Bowers et al., ages 0–99)
        - ``"br_emssb_2021_m"`` / ``"br_emssb_2021_f"`` — BR-EMS Sobrevivência 2021
        - ``"br_emsmt_2021_m"`` / ``"br_emsmt_2021_f"`` — BR-EMS Mortalidade 2021
        - ``"br_emssb_2015_m"`` / ``"br_emssb_2015_f"`` — BR-EMS Sobrevivência 2015
        - ``"br_emsmt_2015_m"`` / ``"br_emsmt_2015_f"`` — BR-EMS Mortalidade 2015
        - ``"br_emssb_2010_m"`` / ``"br_emssb_2010_f"`` — BR-EMS Sobrevivência 2010
        - ``"br_emsmt_2010_m"`` / ``"br_emsmt_2010_f"`` — BR-EMS Mortalidade 2010

        Additional tables (AM92, AF92, soa08, demoUsa, …) can be added by
        running ``scripts/convert_rda_to_parquet.py``, which produces
        ``*.parquet`` files in this directory.
    fractional : FractionalAge
        Fractional-age assumption to attach to the returned LifeTable.

    Returns
    -------
    LifeTable
    """
    # Try CSV (built-in)
    if name in _BUILTIN_TABLES:
        path = _DATA_DIR / _BUILTIN_TABLES[name]
        df = pd.read_csv(path)
        return LifeTable.from_dataframe(
            df, age_col="age", qx_col="qx", name=name, fractional=fractional
        )

    # Try parquet (generated by convert script)
    parquet_path = _DATA_DIR / f"{name}.parquet"
    if parquet_path.exists():
        df = pd.read_parquet(parquet_path)
        # Detect column layout
        if "lx" in df.columns:
            return LifeTable.from_dataframe(
                df, age_col="age", lx_col="lx", name=name, fractional=fractional
            )
        if "qx" in df.columns:
            return LifeTable.from_dataframe(
                df, age_col="age", qx_col="qx", name=name, fractional=fractional
            )
        raise ValueError(f"Parquet file for '{name}' has neither 'lx' nor 'qx' column")

    available = list(_BUILTIN_TABLES.keys()) + [
        p.stem for p in _DATA_DIR.glob("*.parquet")
    ]
    raise ValueError(
        f"Unknown table '{name}'. Available: {available}. "
        "Run scripts/convert_rda_to_parquet.py to import tables from R."
    )


def list_tables() -> list[str]:
    """Return names of all available bundled tables."""
    parquet_names = [p.stem for p in _DATA_DIR.glob("*.parquet")]
    return sorted(list(_BUILTIN_TABLES.keys()) + parquet_names)
